In [19]:
import math
import numpy as np
text_file = open("/Users/panktibhalani/Documents/DM/gaussian.txt", "r");
lines = text_file.readlines()

In [20]:
matrix = []
count = 0
for line in lines:
    values = line.split(" ")
    locallist = []
    locallist.append([float(values[0])])
    locallist.append([float(values[1])])
    matrix.append(locallist)
    

In [21]:
matrix = np.array(matrix)
mean = np.array([[[1],[1]],[[1],[1]]])
variance = np.array([[[2,0],[0,3]],[[3,0],[0,5]]])
N = 6000
M = 2
d = 2
pivalues = np.array([0.3,0.7])
prevlogliklihood = 0.000000000
flag = 1

In [22]:
def EStep(mean, variance, matrix, N, M, d, pivalues):
    dummy = []
    global prevlogliklihood
    global flag
    responsibility = []
    constant = float((math.pi * 2) ** (-d/float(2)))
    for i in range(N):
        
        x = matrix[i]
        temp = []
        totalvalue = float(0)
       
        for m in range(M):
            meu = mean[m]
            
            deter = (np.linalg.det(variance[m])) ** float(-1/2)
            matrix1 = np.subtract(x, meu)
            matrix1T = matrix1.transpose()
            matrix2 = np.linalg.inv(variance[m])
            matrix3 = np.matmul(matrix1T,matrix2)
            finalmatrix = np.linalg.det(np.matmul(matrix3,matrix1))
            expval = np.exp((-1 * finalmatrix)/2)
        
            temp.append(float(float(expval) * float(deter) * float(constant)))
            totalvalue += ((expval * deter * constant) * pivalues[m])
        
        dummy.append(temp)
        ztemp = []
        for j in range(M):
            ztemp.append(pivalues[j] * (float((dummy[i][j])/totalvalue)))
        responsibility.append(ztemp)
    sumtemp = float(0)
    responsibility = np.array(responsibility)
    sumtemp = float(0)
    log_likelihood = np.sum(np.log(np.sum(responsibility.T, axis = 1)))
    print(log_likelihood)
    
    
    
    if round(log_likelihood,3) == round(prevlogliklihood,3):
        flag = 0
    
    prevlogliklihood = log_likelihood
    return responsibility
        
def gaussianmix(mean, variance, matrix, N, M, d, pivalues):
    p = 1
    while(1):
        print("Iterations: " + str(p))
        p+=1
     
        responsibility = EStep(mean, variance, matrix, N, M, d, pivalues)

        varianceN = []
        meannew = []
        pivaluesnew = []
        for m in range(M):

            
            num = np.array([[float(0),float(0)],[float(0),float(0)]])
            ressum = float(0)
            meannewsum = np.array([[float(0)],[float(0)]])
            for i in range(N):
                meannewsum += (matrix[i] * responsibility[i][m])
                ressum += responsibility[i][m]
            meannew.append(meannewsum/float(ressum))
            
            meu = meannew[m]
            
            for i in range(N):
                x = matrix[i]
                matrixtemp = np.subtract(x, meu)
                transposeM = matrixtemp.transpose()
                matrix3 = np.matmul(matrixtemp,transposeM) * responsibility[i][m]
                num += matrix3
                
            
            
            varianceN.append(num/float(ressum))
           
            pivaluesnew.append(ressum/N)

        
        varianceN = np.array(varianceN)
        meannew = np.array(meannew)
        pivaluesnew = np.array(pivaluesnew)
      
    
        if flag == 0:
            print(varianceN)
            print(meannew)
            print(pivaluesnew)
            break
            
        
        mean = meannew
        variance = varianceN
        pivalues = pivaluesnew  

In [10]:
gaussianmix(mean, variance, matrix, N, M, d, pivalues)

Iterations: 1
14.9708695355
Iterations: 2
15.0689601424
Iterations: 3
15.2456479294
Iterations: 4
15.4287964546
Iterations: 5
15.5799316715
Iterations: 6
15.6916021006
Iterations: 7
15.7692429062
Iterations: 8
15.8194040655
Iterations: 9
15.8496498258
Iterations: 10
15.8674915378
Iterations: 11
15.8781974266
Iterations: 12
15.884816963
Iterations: 13
15.8890221188
Iterations: 14
15.8917469222
Iterations: 15
15.8935365781
Iterations: 16
15.8947227795
Iterations: 17
15.8955138232
Iterations: 18
15.8960435172
[[[ 1.00314087  0.02799705]
  [ 0.02799705  2.94118377]]

 [[ 0.97871711  0.49971831]
  [ 0.49971831  1.00303532]]]
[[[ 2.98981666]
  [ 3.05262689]]

 [[ 7.01089028]
  [ 3.98184361]]]
[ 0.33406294  0.66593706]


In [11]:
text_file = open("/Users/panktibhalani/Documents/DM/3gaussian.txt", "r");
lines = text_file.readlines();
matrix = []
count = 0
for line in lines:
    values = line.split(" ")
    locallist = []
    locallist.append([float(values[0])])
    locallist.append([float(values[1])])
    matrix.append(locallist)
    
matrix = np.array(matrix)
mean = np.array([[[1],[1]],[[1],[1]],[[1],[1]]])
variance = np.array([[[1,0],[0,2]],[[2,0],[0,1]],[[1,0],[0,3]]])
N = 10000
M = 3
d = 2
pivalues = np.array([0.3,0.3,0.4])
prevlogliklihood = 0.000000000
flag = 1

gaussianmix(mean, variance, matrix, N, M, d, pivalues)

Iterations: 1
23.435939553
Iterations: 2
23.5068830931
Iterations: 3
23.6400700239
Iterations: 4
23.7823308427
Iterations: 5
23.8989436253
Iterations: 6
23.977273744
Iterations: 7
24.0228688613
Iterations: 8
24.0494019156
Iterations: 9
24.0666633158
Iterations: 10
24.0791371695
Iterations: 11
24.0887519241
Iterations: 12
24.0964365657
Iterations: 13
24.1027117571
Iterations: 14
24.1079080337
Iterations: 15
24.1122538188
Iterations: 16
24.1159158386
Iterations: 17
24.1190202442
Iterations: 18
24.1216649061
Iterations: 19
24.1239271738
Iterations: 20
24.1258690687
Iterations: 21
24.1275409088
Iterations: 22
24.1289839198
Iterations: 23
24.1302321626
Iterations: 24
24.1313139825
Iterations: 25
24.1322531185
Iterations: 26
24.1330695622
Iterations: 27
24.1337802319
Iterations: 28
24.1343995075
[[[ 1.0230907   0.01409265]
  [ 0.01409265  3.34568093]]

 [[ 0.99302816  0.50198022]
  [ 0.50198022  0.99580649]]

 [[ 0.98387344  0.18782082]
  [ 0.18782082  0.97864398]]]
[[[ 3.03274179]
  [ 3.028

In [46]:
from sklearn.mixture import GaussianMixture
from utils import mnist_reader
import collections
train_data, train_labels = mnist_reader.load_mnist('data/', kind='train')
fashmnistnew = train_data/255;
fashmnistnewnp = np.array(fashmnistnew)

gmmresultfsh = GaussianMixture(n_components=10, covariance_type='diag').fit(fashmnistnewnp)
print(gmmresultfsh.converged_)
print(gmmresultfsh.covariances_.shape)
print(gmmresultfsh.means_.shape)
print(gmmresultfsh.weights_)

True
(10, 784)
(10, 784)
[ 0.04019858  0.12613677  0.09306877  0.12821217  0.04879761  0.10998464
  0.19108298  0.05476666  0.06242058  0.14533123]


In [36]:
def calculateEvaluationmatrix(hashmap, givenlabels,data):
    maxclus = []
    hasmap = {}
    ginindex = []
    MJ = []
    for key in hashmap.keys():
        temp = {}
        for datapoint in hashmap[key]:

            templabel = givenlabels[datapoint]
            if templabel in temp:
                temp[templabel] += 1
            else:
                temp[templabel] = 1
        datapercen = float(0)
        for keytemp in temp.keys():
            datapercen += ((temp[keytemp]/float(len(hashmap[key]))) ** 2)

        ginindex.append(float(1)-float(datapercen))
        MJ.append(float(len(hashmap[key])))
        maxclus.append(max(temp.items(), key=operator.itemgetter(1))[1])
    
    summation = 0
    for a in maxclus:
        summation += a

    ginisum = float(0)
    for i in range(len(ginindex)):
        ginisum += ginindex[i] * MJ[i]


    print("Purity: " + str(summation/data.shape[0]))

    print("Giniindex: " + str(ginisum/data.shape[0]))

In [37]:
hashmap = {}
datapoint = 0
import operator
for i in gmmresultfsh.predict(fashmnistnewnp):
    if i in hashmap:
        hashmap[i].append(datapoint)
    else:
        list1 = [datapoint]
        hashmap[i] = list1[:]
    datapoint += 1

calculateEvaluationmatrix(hashmap,train_labels,fashmnistnewnp )

Purity: 0.5158333333333334
Giniindex: 0.5989671793666372


In [45]:
text_file = open("/Users/panktibhalani/Documents/DM/HW2/spambase.txt", "r");
lines = text_file.readlines();
matrix = []
count = 0
labels = []
for line in lines:
    values = line.split(",")
    locallist = []
    for val in values:
        locallist.append(val)
    
    labels.append(locallist[len(locallist) - 1])
    del locallist[-1]
    matrix.append(locallist)

gmmresultfsh = GaussianMixture(n_components=10, covariance_type='diag').fit(matrix)
print(gmmresultfsh.converged_)
print(gmmresultfsh.covariances_.shape)
print(gmmresultfsh.means_.shape)
print(gmmresultfsh.weights_)


hashmap = {}
datapoint = 0
for i in gmmresultfsh.predict(matrix):
    if i in hashmap:
        hashmap[i].append(datapoint)
    else:
        list1 = [datapoint]
        hashmap[i] = list1[:]
    datapoint += 1

calculateEvaluationmatrix(hashmap,labels,np.array(matrix))

True
(10, 57)
(10, 57)
[  8.37098347e-02   1.17343206e-01   2.16923822e-01   2.17344056e-04
   2.17344056e-04   6.52032167e-04   9.30659023e-02   2.93628497e-01
   4.69713380e-02   1.47270681e-01]
Purity: 0.8050423820908498
Giniindex: 0.2913941013064441
